pub struct Element {
    pub symbol: &'static str,
    pub possible_valence: &'static [i8],
    pub electronegativity: f32,
    pub max_valence: MaxValence,
}

pub enum MaxValence {
    Two = 2,
    Eight = 8,
}

pub const PERIODIC_TABLE: [Element; 60] = [
    Element {
        symbol: "H",
        possible_valence: &[-1, 1],
        electronegativity: 2.20,
        max_valence: MaxValence::Two,
    },
    Element {
        symbol: "He",
        possible_valence: &[0],
        electronegativity: 0.00,
        max_valence: MaxValence::Two,
    },
    Element {
        symbol: "Li",
        possible_valence: &[1],
        electronegativity: 0.98,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Be",
        possible_valence: &[2],
        electronegativity: 1.57,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "B",
        possible_valence: &[3],
        electronegativity: 2.04,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "C",
        possible_valence: &[-4, 4],
        electronegativity: 2.55,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "N",
        possible_valence: &[-3, 3, 5],
        electronegativity: 3.04,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "O",
        possible_valence: &[-2],
        electronegativity: 3.44,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "F",
        possible_valence: &[-1],
        electronegativity: 3.98,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ne",
        possible_valence: &[0],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Na",
        possible_valence: &[1],
        electronegativity: 0.93,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Mg",
        possible_valence: &[2],
        electronegativity: 1.31,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Al",
        possible_valence: &[3],
        electronegativity: 1.61,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Si",
        possible_valence: &[-4, 4],
        electronegativity: 1.90,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "P",
        possible_valence: &[-3, 3, 5],
        electronegativity: 2.19,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "S",
        possible_valence: &[-2, 2, 4, 6],
        electronegativity: 2.58,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Cl",
        possible_valence: &[-1, 1, 3, 5, 7],
        electronegativity: 3.16,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ar",
        possible_valence: &[0],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "K",
        possible_valence: &[1],
        electronegativity: 0.82,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ca",
        possible_valence: &[2],
        electronegativity: 1.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Sc",
        possible_valence: &[3],
        electronegativity: 1.36,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ti",
        possible_valence: &[4],
        electronegativity: 1.54,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "V",
        possible_valence: &[5],
        electronegativity: 1.63,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Cr",
        possible_valence: &[3, 6],
        electronegativity: 1.66,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Mn",
        possible_valence: &[2, 4, 7],
        electronegativity: 1.55,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Fe",
        possible_valence: &[2, 3],
        electronegativity: 1.83,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Co",
        possible_valence: &[2, 3],
        electronegativity: 1.88,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ni",
        possible_valence: &[2],
        electronegativity: 1.91,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Cu",
        possible_valence: &[2],
        electronegativity: 1.90,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Zn",
        possible_valence: &[2],
        electronegativity: 1.65,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Pm",
        possible_valence: &[3],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Sm",
        possible_valence: &[3],
        electronegativity: 1.17,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Eu",
        possible_valence: &[2, 3],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Gd",
        possible_valence: &[3],
        electronegativity: 1.20,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Tb",
        possible_valence: &[3],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Dy",
        possible_valence: &[3],
        electronegativity: 1.22,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ho",
        possible_valence: &[3],
        electronegativity: 1.23,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Er",
        possible_valence: &[3],
        electronegativity: 1.24,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Tm",
        possible_valence: &[3],
        electronegativity: 1.25,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Yb",
        possible_valence: &[3],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Lu",
        possible_valence: &[3],
        electronegativity: 1.27,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Hf",
        possible_valence: &[4],
        electronegativity: 1.30,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ta",
        possible_valence: &[5],
        electronegativity: 1.50,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "W",
        possible_valence: &[4, 6],
        electronegativity: 2.36,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Re",
        possible_valence: &[4],
        electronegativity: 1.90,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Os",
        possible_valence: &[4],
        electronegativity: 2.20,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ir",
        possible_valence: &[3, 4],
        electronegativity: 2.20,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Pt",
        possible_valence: &[2, 4],
        electronegativity: 2.28,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Au",
        possible_valence: &[3],
        electronegativity: 2.54,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Hg",
        possible_valence: &[1, 2],
        electronegativity: 2.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Tl",
        possible_valence: &[1, 3],
        electronegativity: 1.62,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Pb",
        possible_valence: &[2, 4],
        electronegativity: 2.33,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Bi",
        possible_valence: &[3],
        electronegativity: 2.02,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Po",
        possible_valence: &[-2, 2, 4],
        electronegativity: 2.02,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "At",
        possible_valence: &[-1, 1],
        electronegativity: 2.20,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Rn",
        possible_valence: &[2],
        electronegativity: 0.00,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Fr",
        possible_valence: &[1],
        electronegativity: 0.70,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ra",
        possible_valence: &[2],
        electronegativity: 0.90,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Ac",
        possible_valence: &[3],
        electronegativity: 1.10,
        max_valence: MaxValence::Eight,
    },
    Element {
        symbol: "Th",
        possible_valence: &[4],
        electronegativity: 1.30,
        max_valence: MaxValence::Eight,
    },
];
